[package]
name = "rust-chat"
version = "0.2.0"
authors = ["Nikita Baksalyar <nikita.baksalyar@gmail.com>"]

[dependencies]
http-muncher = "0.2.*"
sha1 = "0.1.*"
rustc-serialize = "0.3.*"
byteorder = "0.3.*"

[dependencies.mio]
git = "https://github.com/carllerche/mio"


